"""empty message

Revision ID: af6ffc2a7b3d
Revises: 4297ba882643
Create Date: 2023-03-21 14:16:03.088830

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af6ffc2a7b3d'
down_revision = '4297ba882643'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'favorite', 'person', ['person_id'], ['id'])
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_id'], ['id'])
    op.drop_constraint('person_user_id_fkey', 'person', type_='foreignkey')
    op.drop_column('person', 'user_id')
    op.drop_constraint('planet_user_id_fkey', 'planet', type_='foreignkey')
    op.drop_column('planet', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('planet', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('planet_user_id_fkey', 'planet', 'user', ['user_id'], ['id'])
    op.add_column('person', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('person_user_id_fkey', 'person', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    # ### end Alembic commands ###
